### ISSUE TITLE
getBrowserVersion is null for Edge/12.21231

### ISSUE THREAD

**Issue by lkyprogramer** [HaraldWalker/user-agent-utils#117] opened 2015-08-17 07:59 UTC
> User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.21231

i took some User Agent Strings of Edge browser from this site  [http://www.webapps-online.com/online-tools/user-agent-strings/dv/browser646202/edge-browser](http://www.webapps-online.com/online-tools/user-agent-strings/dv/browser646202/edge-browser) to test,also found version is null.

**Comment by HaraldWalker** [comment] 2015-08-17 08:02
Duplicate of #113.
Already fixed in SNAPSHOT release.

**Closed by HaraldWalker** 2015-08-17 08:02 UTC
